### ISSUE TITLE
Capital D in plex font has space to the left of it that causes it to not display nicely

### ISSUE THREAD

**Issue by JoeHughes-IBM** [IBM/type#135]
As you can see when highlighted there is a small amount of space added to the left of the D.  This causes it to never line up.  There is nothing in our CSS adding this space.

<img width="491" alt="screen shot 2018-02-20 at 9 54 36 am" src="https://user-images.githubusercontent.com/21244279/36430834-1383a96e-1624-11e8-98e8-0f0db07c3c09.png">

**Comment by BoldMonday** [comment]
First of all, your example does not show Plex, but Helvetica. But you will see the same thing happening with Plex though, and pretty much every other font out there.

In order to avoid that two letters stick together they need to have a bit of margin in between. This is called spacing. Therefore every letter has a bit of whitespace on the left and right.

**Comment by JoeHughes-IBM** [comment]
Sorry didn't realize I copied the wrong image in.  However, yes saw it in both.  I've not experience this misalignment on other fonts on the left.
